name: GitHub Profile Summary Cards

# Trigger manually or on schedule
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # runs daily at midnight UTC

jobs:
  generate-cards:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Step 2: Generate GitHub Profile Summary Cards
      - name: Generate Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: maroayman
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: main
          UTC_OFFSET: 0
          AUTO_PUSH: true
