name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *"   # Auto run every 12 hours
  workflow_dispatch:          # Manual run

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: ${{ github.repository_owner }}

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update summary cards" || echo "No changes"
          git push
